module.exports = {
    applicationPermission: require("./applicationpermission"),
    audit: require("./audit"),
    automoderation: require("./automoderation"),
    button: require("./button"),
    channelPermission: require("./channelpermission"),
    channels: require("./channels"),
    command: require("./command"),
    event: require("./event"),
    forum: require("./forum"),
    guild: require("./guild"),
    integration: require("./integration"),
    intents: require("./intents"),
    invite: require("./invite"),
    message: require("./message"),
    option: require("./option"),
    permissions: require("./permissions"),
    textInput: require("./textinput"),
    userbadges: require("./userbadges"),
    webhook: require("./webhook"),
    
}