const colors = {
    DEFAULT: 0x000000,
    WHITE: 0xffffff,
    AQUA: 0x1abc9c,
    GREEN: 0x57f287,
    BLUE: 0x3498db,
    YELLOW: 0xfee75c,
    PURPLE: 0x9b59b6,
    LUMINOUS_VIVID_PINK: 0xe91e63,
    FUCHSIA: 0xeb459e,
    GOLD: 0xf1c40f,
    ORANGE: 0xe67e22,
    RED: 0xed4245,
    GREY: 0x95a5a6,
    NAVY: 0x34495e,
    DARK_AQUA: 0x11806a,
    DARK_GREEN: 0x1f8b4c,
    DARK_BLUE: 0x206694,
    DARK_PURPLE: 0x71368a,
    DARK_VIVID_PINK: 0xad1457,
    DARK_GOLD: 0xc27c0e,
    DARK_ORANGE: 0xa84300,
    DARK_RED: 0x992d22,
    DARK_GREY: 0x979c9f,
    DARKER_GREY: 0x7f8c8d,
    LIGHT_GREY: 0xbcc0c0,
    DARK_NAVY: 0x2c3e50,
    BLURPLE: 0x5865f2,
    GREYPLE: 0x99aab5,
    DARK_BUT_NOT_BLACK: 0x2c2f33,
    NOT_QUITE_BLACK: 0x23272a,
};

const languagesAvailable = [
    {id: "id", name: "Indonesian"},
    {id: "da", name: "Danish"},
    {id: "de", name: "German"},
    {id: "en-GB", name: "English, UK"}, 
    {id: "en-US", name: "English, US"}, 
    {id: "es-ES", name: "Spanish"},
    {id: "fr", name: "French"},
    {id: "hr", name: "Croatian"},
    {id: "it", name: "Italian"},
    {id: "lt", name: "Lithuanian"},
    {id: "hu", name: "Hungarian"},
    {id: "nl", name: "Dutch"},
    {id: "no", name: "Norwegian"},
    {id: "pl", name: "Polish"},
    {id: "pt-BR", name: "Portuguese, Brazilian"},
    {id: "ro", name: "Romanian"},
    {id: "fi", name: "Finnish"},
    {id: "sv-SE", name: "Swedish"},
    {id: "vi", name: "Vietnamese"},
    {id: "tr", name: "Turkish"},
    {id: "cs", name: "Czech"},
    {id: "el", name: "Greek"},
    {id: "bg", name: "Bulgarian"},
    {id: "ru", name: "Russian"},
    {id: "uk", name: "Ukrainian"},
    {id: "hi", name: "Hindi"},
    {id: "th", name: "Thai"},
    {id: "zh-CN", name: "Chinese"},
    {id: "ja", name: "Japanese"},
    {id: "zh-TW", name: "Chinese, Taiwan"},
    {id: "ko", name: "Korean"}
]

const priviledgedIntents = [
    {
        intentName: 'GUILD_MEMBERS',
        flagName: 'GatewayGuildMembersLimited',
    },
    {
        intentName: 'MESSAGE_CONTENT',
        flagName: 'GatewayMessageContentLimited',
    },
    {
        intentName: 'GUILD_PRESENCES',
        flagName: 'GatewayPresenceLimited',
    },
]

module.exports =  {
    colors, 
    languagesAvailable,
    priviledgedIntents,
}